name: 'Get release info'

description: 'Get release info'

inputs:
  github_token:
    description: 'Github token'
    required: true

outputs:
  body:
    description: 'Release body'
  name:
    description: 'Release name'
  tag_name:
    description: 'Release tag name'
  url:
    description: 'Release url'
  prerelease:
    description: 'Is prerelease or not'
  author_login:
    description: 'Author login'
  author_avatar:
    description: 'Author avatar'
  author_url:
    description: 'Author url'
runs:
  using: 'node16'
  main: '.dist/index.js'
